import "./globals.css";
import Header from "../app/components/header/hedaer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
